- name: remove source directory
  ansible.builtin.file:
    path: "{{ APP_LOCATION }}"
    state: absent

- name: create app directory
  ansible.builtin.file:
     path: "{{ APP_LOCATION }}"
     stste: present

- name: download code unarchive
  ansible.builtin.unarchive:
     src: "{{ https://expense-builds.s3.us-east-1.amazonaws.com/expense-{{ COMPONENT }}-v2.zip }}"
     dest: "{{ APP_LOCATION }}"
     remote_src: yes
   